import { useState } from "react";
import { useNavigate } from "react-router-dom";
import PageHeader from "../components/PageHeader.jsx";
import StepIndicator from "../components/StepIndicator.jsx";

const SUMMARY_FIELDS = [
  { key: "symptoms", label: "Reported Symptoms" },
  { key: "duration", label: "Duration" },
  { key: "severity", label: "Severity" },
  { key: "medication", label: "Medication Taken" },
];

const DEFAULT_SUMMARY = {
  symptoms: "Persistent headache and mild fever for the past 2 days, worsening in the evening.",
  duration: "2 days",
  severity: "6 / 10",
  medication: "Paracetamol, once, with mild relief",
};

// Combines the structured summary into one block of text for editing.
function toText(summary) {
  return SUMMARY_FIELDS.map((f) => `${f.label}: ${summary[f.key]}`).join("\n");
}

// Parses the edited text block back into structured fields, keyed by label.
function fromText(text) {
  const parsed = { ...DEFAULT_SUMMARY };
  text.split("\n").forEach((line) => {
    const [rawLabel, ...rest] = line.split(":");
    const field = SUMMARY_FIELDS.find(
      (f) => f.label.toLowerCase() === rawLabel.trim().toLowerCase()
    );
    if (field) parsed[field.key] = rest.join(":").trim();
  });
  return parsed;
}

export default function PatientSummary() {
  const navigate = useNavigate();
  const [summary, setSummary] = useState(DEFAULT_SUMMARY);
  const [draftText, setDraftText] = useState(toText(DEFAULT_SUMMARY));
  const [isEditing, setIsEditing] = useState(false);

  const handleEdit = () => {
    setDraftText(toText(summary));
    setIsEditing(true);
  };

  const handleSave = () => {
    setSummary(fromText(draftText));
    setIsEditing(false);
  };

  const handleCancel = () => {
    setDraftText(toText(summary));
    setIsEditing(false);
  };

  return (
    <div className="min-h-screen bg-clinical-50">
      <PageHeader
        back={{ to: "/followup", label: "Back" }}
        profile={{ to: "/patient-dashboard", label: "My profile" }}
      />

      <main className="mx-auto max-w-2xl px-5 py-12 sm:px-8">
        <StepIndicator current="summary" />

        <h1 className="text-center font-display text-3xl font-extrabold text-clinical-900">
          Your summary is ready
        </h1>
        <p className="mt-2 text-center text-muted">
          Review it below, then send it to your doctor ahead of the consultation.
        </p>

        <div className="surface-card mt-8">
          <div className="mb-5 flex items-center justify-between">
            <span className="rounded-full bg-clinical-100 px-3 py-1 text-xs font-semibold text-clinical-700">
              Sample Summary
            </span>
            <div className="flex items-center gap-3">
              <span className="text-xs text-muted">Generated by HealEasy AI</span>
              {!isEditing && (
                <button
                  type="button"
                  onClick={handleEdit}
                  className="text-xs font-semibold text-clinical-700 hover:text-clinical-800"
                >
                  Edit
                </button>
              )}
            </div>
          </div>

          {isEditing ? (
            <>
              <label className="field-label" htmlFor="summaryEdit">
                Edit summary
              </label>
              <textarea
                id="summaryEdit"
                value={draftText}
                onChange={(e) => setDraftText(e.target.value)}
                rows={6}
                className="field-input resize-none text-sm"
              />
              <div className="mt-4 flex gap-3">
                <button
                  type="button"
                  onClick={handleSave}
                  className="btn-primary flex-1 py-3 text-sm"
                >
                  Save
                </button>
                <button
                  type="button"
                  onClick={handleCancel}
                  className="btn-secondary flex-1 py-3 text-sm"
                >
                  Cancel
                </button>
              </div>
            </>
          ) : (
            <dl className="space-y-4 text-sm">
              {SUMMARY_FIELDS.map((f) => (
                <div key={f.key}>
                  <dt className="font-display font-bold text-clinical-800">{f.label}</dt>
                  <dd className="mt-1 text-muted">{summary[f.key]}</dd>
                </div>
              ))}
            </dl>
          )}
        </div>

        <button
          type="button"
          onClick={() => navigate("/doctor-login")}
          className="btn-primary mt-6 w-full py-3.5 text-base"
        >
          Send to Doctor
        </button>
      </main>
    </div>
  );
}
