import { useState } from "react";
import { useNavigate } from "react-router-dom";
import PageHeader from "../components/PageHeader.jsx";
import StepIndicator from "../components/StepIndicator.jsx";
import Toast from "../components/Toast.jsx";
import { useSession } from "../context/SessionContext.jsx";

export default function PatientSummary() {
  const navigate = useNavigate();
  const { session } = useSession();

  const raw = session.summary;
  const [error, setError] = useState(null);

  // Normalise whatever the backend returns into a flat string or key/value list
  const fields = raw
    ? typeof raw === "string"
      ? [{ label: "Summary", value: raw }]
      : Object.entries(raw).map(([k, v]) => ({
          label: k.replace(/([A-Z])/g, " $1").replace(/^./, (s) => s.toUpperCase()),
          value: Array.isArray(v) ? v.join(", ") : String(v),
        }))
    : null;

  if (!fields) {
    return (
      <div className="min-h-screen bg-clinical-50">
        <PageHeader back={{ to: "/followup", label: "Back" }} />
        <main className="mx-auto max-w-2xl px-5 py-16 text-center">
          <p className="text-muted">No summary available. Please go back and complete the follow-up questions.</p>
          <button onClick={() => navigate("/followup")} className="btn-primary mt-6">
            Back to Follow-up
          </button>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-clinical-50">
      <PageHeader
        back={{ to: "/followup", label: "Back" }}
        profile={{ to: "/patient-dashboard", label: "My profile" }}
      />

      {error && <Toast message={error} onClose={() => setError(null)} />}

      <main className="mx-auto max-w-2xl px-5 py-12 sm:px-8">
        <StepIndicator current="summary" />

        <h1 className="text-center font-display text-3xl font-extrabold text-clinical-900">
          Your summary is ready
        </h1>
        <p className="mt-2 text-center text-muted">
          Review it below, then send it to your doctor ahead of the consultation.
        </p>

        <div className="surface-card mt-8">
          <div className="mb-5 flex items-center justify-between">
            <span className="rounded-full bg-clinical-100 px-3 py-1 text-xs font-semibold text-clinical-700">
              AI Summary
            </span>
            <span className="text-xs text-muted">Generated by HealEasy AI</span>
          </div>

          <dl className="space-y-4 text-sm">
            {fields.map((f) => (
              <div key={f.label}>
                <dt className="font-display font-bold text-clinical-800">{f.label}</dt>
                <dd className="mt-1 text-muted">{f.value}</dd>
              </div>
            ))}
          </dl>
        </div>

        <button type="button" onClick={() => navigate("/doctor-login")}
          className="btn-primary mt-6 w-full py-3.5 text-base">
          Send to Doctor
        </button>
      </main>
    </div>
  );
}
